# Bridge to the Ansible playbook: render inventory/aws/ with public IPs
# for SSH and private IPs as crdb_advertise (all CRDB traffic rides the
# peered private mesh).

locals {
  all_nodes = concat(module.use1.nodes, module.use2.nodes, module.usw2.nodes)
}

resource "local_file" "ansible_inventory" {
  filename        = "${path.module}/../../ansible/inventory/aws/hosts.ini"
  file_permission = "0644"
  content         = <<-EOT
    # Generated by terraform/aws — do not edit by hand.
    [crdb]
    %{~for n in local.all_nodes~}
    ${n.name} ansible_host=${n.public_ip} crdb_advertise=${n.private_ip} crdb_region=${n.region} crdb_zone=${n.az}
    %{~endfor~}

    [crdb:vars]
    ansible_user=ubuntu
    ansible_ssh_common_args=-o StrictHostKeyChecking=accept-new

    # One KDC per region, colocated on the region's first CRDB node.
    [kdc]
    %{~for r in distinct([for n in local.all_nodes : n.region])~}
    ${[for n in local.all_nodes : n.name if n.region == r][0]}
    %{~endfor~}

    [kdc:vars]
    ansible_user=ubuntu
    ansible_ssh_common_args=-o StrictHostKeyChecking=accept-new
  EOT
}

resource "local_file" "ansible_group_vars" {
  filename        = "${path.module}/../../ansible/inventory/aws/group_vars/crdb.yml"
  file_permission = "0644"
  content         = <<-EOT
    # Generated by terraform/aws — sized for ${var.instance_type}.
    crdb_version: "25.2.2"
    crdb_arch: "${var.crdb_arch}"
    crdb_local_arch: "linux-amd64"  # controller (this dev box) stays x86
    crdb_checksum: ""
    crdb_user: cockroach
    crdb_store_dir: /var/lib/cockroach
    crdb_certs_dir: /etc/cockroach/certs
    crdb_sql_port: 26257
    crdb_http_port: 8080
    crdb_cache: 2GiB
    crdb_max_sql_memory: 2GiB
    crdb_krb5_database: krb5
    crdb_krb5_user: krb5kdc
    crdb_primary_region: ""
    crdb_local_secrets: "{{ playbook_dir }}/secrets"
    crdb_local_cache: "{{ playbook_dir }}/.cache"
  EOT
}

output "nodes" {
  value = {
    for n in local.all_nodes : n.name => {
      public_ip  = n.public_ip
      private_ip = n.private_ip
      region     = n.region
      az         = n.az
    }
  }
}

output "next_steps" {
  value = <<-EOT
    inventory written to ansible/inventory/aws/
    1. wait ~1 min for cloud-init, then:
       cd ../../ansible && ansible-playbook -i inventory/aws/hosts.ini site.yml
    2. teardown: terraform destroy (spot spend stops there)
  EOT
}
